export type Theme = "light" | "dark";

export type ActiveView =
  | "landing"
  | "dashboard"
  | "login"
  | "signup"
  | "forgot-password"
  | "reset-password"
  | "profile"
  | "settings-profile"
  | "settings-ai-providers"
  | "settings-workspace"
  | "settings-billing"
  | "pricing"
  | "generator"
  | "projects"
  | "history"
  | "review"
  | "execution"
  | "chat"
  | "repository-application"
  | "repository-automation"
  | "repository-activity"
  | "repository-impact"
  | "repository-playwright"
  | "workspace"
  | "analytics";
